CREATE TABLE "certificates" (
	"id" serial PRIMARY KEY NOT NULL,
	"examid" text NOT NULL,
	"verification_code" varchar(100) NOT NULL,
	"employee_id" varchar(100) NOT NULL,
	"name" varchar(255) NOT NULL,
	"email" varchar(255),
	"phone" varchar(30),
	"designation" varchar(255) NOT NULL,
	"department" varchar(255),
	"internship_type" varchar(100),
	"start_date" date NOT NULL,
	"end_date" date NOT NULL,
	"duration" varchar(100),
	"performance_grade" varchar(100),
	"university_name" varchar(255),
	"college_name" varchar(255),
	"course" varchar(100),
	"branch" varchar(100),
	"semester" varchar(50),
	"enrollment_number" varchar(100),
	"project_name" varchar(255),
	"technologies" jsonb,
	"skills" jsonb,
	"issue_date" date NOT NULL,
	"email_status" varchar(30) DEFAULT 'not_available' NOT NULL,
	"certificate_url" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "certificates_verification_code_unique" UNIQUE("verification_code"),
	CONSTRAINT "certificates_examid_employee_id_unique" UNIQUE("examid","employee_id")
);
--> statement-breakpoint
CREATE TABLE "offer_letters" (
	"id" serial PRIMARY KEY NOT NULL,
	"examid" text NOT NULL,
	"offer_letter_id" varchar(100) NOT NULL,
	"employee_id" varchar(100),
	"name" varchar(255) NOT NULL,
	"email" varchar(255),
	"phone" varchar(30),
	"designation" varchar(255) NOT NULL,
	"department" varchar(255),
	"internship_type" varchar(100),
	"start_date" date NOT NULL,
	"end_date" date,
	"duration" varchar(100),
	"stipend" varchar(100),
	"work_mode" varchar(50),
	"issue_date" date NOT NULL,
	"offer_letter_url" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"work_hours" varchar(50) DEFAULT '8 hours per day',
	"weekly_hours" integer DEFAULT 40,
	"shift_start_time" varchar(20) DEFAULT '10:00 AM',
	"shift_end_time" varchar(20) DEFAULT '6:00 PM',
	"break_duration" varchar(50) DEFAULT '45 Minutes',
	"reporting_manager" varchar(255) DEFAULT 'Rohit Verma',
	"reporting_manager_designation" varchar(255) DEFAULT 'Director',
	"reporting_manager_email" varchar(255) DEFAULT 'support@sqrock.cloud',
	"university_name" varchar(255),
	"course" varchar(100),
	"branch" varchar(100),
	"semester" varchar(50),
	"minimum_attendance" integer DEFAULT 80,
	"allowed_leaves" integer DEFAULT 3,
	"notice_period" varchar(50) DEFAULT '7 Days',
	"hr_name" varchar(255) DEFAULT 'SANIYA KHAN',
	"hr_designation" varchar(255) DEFAULT 'Co-Founder',
	"hr_email" varchar(255) DEFAULT 'support@sqrock.cloud',
	"hr_phone" varchar(30) DEFAULT '+91 9876543210',
	"authorized_person_name" varchar(255) DEFAULT 'Rohit Verma',
	"authorized_person_designation" varchar(255) DEFAULT 'Director',
	"authorized_signature" text DEFAULT '/rohit.png',
	"company_stamp" text DEFAULT '/stamp.png',
	"responsibilities" jsonb,
	"learning_objectives" jsonb,
	"technologies" jsonb,
	"terms_and_conditions" jsonb,
	"company_assets" jsonb,
	"confidentiality_clause" text,
	"intellectual_property_clause" text,
	"termination_policy" text,
	"code_of_conduct" text,
	"performance_review" text,
	"completion_criteria" text,
	"certificate_eligibility" text,
	"leave_policy" text,
	CONSTRAINT "offer_letters_offer_letter_id_unique" UNIQUE("offer_letter_id")
);
